version: '3'

networks:
  budibase_backend:
    external: true

services:
  lanoel:
    container_name: lanoel
    image: registry.justmammoth.us/lanoel:${IMAGE_VERSION}
    restart: unless-stopped
    networks:
      - budibase_backend
